Repository codemod/codemod, pull requests merged in 2024-06, with the labels that each got.

#791 [docs] update cli docs
  apps/docs/deploying-codemods/cli.mdx
Labels: documentation

#820 [docs] adjust naming
  apps/docs/building-codemods/getting-started.mdx
  apps/docs/codemod-registry/introduction.mdx
  apps/docs/codemod-registry/publishing-codemods.mdx
  apps/docs/deploying-codemods/cli.mdx
  apps/docs/deploying-codemods/introduction.mdx
  apps/docs/deploying-codemods/vsce.mdx
Labels: documentation

#812 [docs] fix: typo
  apps/docs/codemod-registry/publishing-codemods.mdx
Labels: documentation, ❤️ community contribution

#840 Update README.md
  README.md
Labels: documentation

#828 [docs] reorganize & update docs
  apps/docs/building-codemods/codemod-studio.mdx
  apps/docs/building-codemods/getting-started.mdx
  apps/docs/codemod-registry/introduction.mdx
  apps/docs/codemod-registry/publishing-codemods.mdx
  apps/docs/deploying-codemods/cli-overview.mdx
  apps/docs/deploying-codemods/cli.mdx
  apps/docs/deploying-codemods/introduction.mdx
  apps/docs/deploying-codemods/vsce.mdx
  apps/docs/images/codemod-registry/codemod-registry-dark.svg
  apps/docs/images/codemod-registry/codemod-registry-light.svg
  apps/docs/images/deploying-codemods/cli/codemod-cli-dark.svg
  apps/docs/images/deploying-codemods/cli/codemod-cli-light.svg
  apps/docs/images/deploying-codemods/vsce/codemod-vsce-dark.svg
  apps/docs/images/deploying-codemods/vsce/codemod-vsce-light.svg
  apps/docs/introduction.mdx
  apps/docs/mint.json
  apps/docs/platform/build.mdx
  apps/docs/platform/manage.mdx
  apps/docs/platform/run.mdx
  apps/docs/platform/share.mdx
Labels: documentation

#845 [docs] shorten share intro
  apps/docs/platform/share.mdx
Labels: documentation

#844 [docs] add codemod publish source option
  apps/docs/deploying-codemods/cli.mdx
Labels: documentation

#864 Create CONTRIBUTOR_LICENSE_AGREEMENT.md
  CONTRIBUTOR_LICENSE_AGREEMENT.md
Labels: documentation

#874 Update CONTRIBUTOR_LICENSE_AGREEMENT.md
  CONTRIBUTOR_LICENSE_AGREEMENT.md
Labels: documentation

#881 [docs] fix: remove leftover overview link
  apps/docs/codemod-registry/introduction.mdx
Labels: documentation

#882 [docs] fix typo
  apps/docs/guides/migrations/msw-v1-v2.mdx
  apps/docs/guides/migrations/react-18-19.mdx
Labels: documentation

#884 [docs] update run section
  apps/docs/platform/run.mdx
Labels: documentation

#891 [docs] fix codemod feedback command
  apps/docs/deploying-codemods/cli.mdx
Labels: documentation

#967 Create Codemod Studio Issue template
  .github/ISSUE_TEMPLATE/studio-bug
Labels: documentation

#886 feat: add codemod for default value updates
  packages/codemods/nuxt/4/default-data-error-value/.codemodrc.json
  packages/codemods/nuxt/4/default-data-error-value/.gitignore
  packages/codemods/nuxt/4/default-data-error-value/LICENSE
  packages/codemods/nuxt/4/default-data-error-value/README.md
  packages/codemods/nuxt/4/default-data-error-value/__testfixtures__/fixture1.input.ts
  packages/codemods/nuxt/4/default-data-error-value/__testfixtures__/fixture1.output.ts
  packages/codemods/nuxt/4/default-data-error-value/package.json
  packages/codemods/nuxt/4/default-data-error-value/src/index.ts
  packages/codemods/nuxt/4/default-data-error-value/tsconfig.json
  packages/codemods/nuxt/4/default-data-error-value/vitest.config.ts
Labels: new-codemod, nuxt, ❤️ community contribution

#973 [codemods][Nuxt] feat: add codemod to update the deprecated dedupe values
  apps/frontend/app/(website)/studio/src/components/button/IconButton.tsx
  packages/codemods/nuxt/4/deprecated-dedupe-value/.codemodrc.json
  packages/codemods/nuxt/4/deprecated-dedupe-value/.gitignore
  packages/codemods/nuxt/4/deprecated-dedupe-value/LICENSE
  packages/codemods/nuxt/4/deprecated-dedupe-value/README.md
  packages/codemods/nuxt/4/deprecated-dedupe-value/__testfixtures__/fixture1.input.ts
  packages/codemods/nuxt/4/deprecated-dedupe-value/__testfixtures__/fixture1.output.ts
  packages/codemods/nuxt/4/deprecated-dedupe-value/package.json
  packages/codemods/nuxt/4/deprecated-dedupe-value/src/index.ts
  packages/codemods/nuxt/4/deprecated-dedupe-value/tsconfig.json
  packages/codemods/nuxt/4/deprecated-dedupe-value/vitest.config.ts
  pnpm-lock.yaml
Labels: nuxt, ❤️ community contribution
