Repository codemod/codemod, pull requests merged in 2024-08, with the labels that each got.

#1227 fix(codemod): support partial defaultProps
  packages/codemods/react/19/replace-default-props/__testfixtures__/partial-default-props.input.tsx
  packages/codemods/react/19/replace-default-props/__testfixtures__/partial-default-props.output.tsx
  packages/codemods/react/19/replace-default-props/src/index.ts
  packages/codemods/react/19/replace-default-props/test/test.ts
Labels: ❤️ community contribution, codemod-issue

#1240 docs: revamp workflow engine structure
  apps/docs/api-reference/command/exec.mdx
  apps/docs/api-reference/file/dirs.mdx
  apps/docs/api-reference/file/files.mdx
  apps/docs/api-reference/file/move.mdx
  apps/docs/api-reference/git/branch.mdx
  apps/docs/api-reference/git/clone.mdx
  apps/docs/api-reference/git/commit.mdx
  apps/docs/api-reference/git/push.mdx
  apps/docs/api-reference/transformation/addimport.mdx
  apps/docs/api-reference/transformation/astgrep/overview.mdx
  apps/docs/api-reference/transformation/astgrep/reference.mdx
  apps/docs/api-reference/transformation/codemod.mdx
  apps/docs/api-reference/transformation/jscodeshift.mdx
  apps/docs/api-reference/transformation/jsfam.mdx
  apps/docs/api-reference/transformation/removeimport.mdx
  apps/docs/deploying-codemods/workflow-engine.mdx
  apps/docs/guides/building-codemods/codemod2.mdx
  apps/docs/guides/engines/workflow-engine.mdx
  apps/docs/guides/engines/workflow-engine/api-reference.mdx
  apps/docs/guides/introduction.mdx
  apps/docs/mint.json
  apps/docs/more-resources/legal/telemetry-compliance.mdx
Labels: documentation

#1279 docs: add logs command
  apps/docs/deploying-codemods/cli.mdx
Labels: documentation

#1275 refactor: use-template-literals: reuse isStringLiteral
  packages/codemods/typescript/use-template-literals/src/index.ts
Labels: ❤️ community contribution, codemod improvement

#1285 docs: updates and improvements
  apps/docs/building-codemods/codemod-studio.mdx
  apps/docs/deploying-codemods/cli.mdx
  apps/docs/guides/building-codemods/build-package.mdx
  apps/docs/guides/building-codemods/package-requirements.mdx
  apps/docs/images/codemod-studio/studio-export.mp4
  apps/docs/images/codemod-studio/studio-publish.mp4
  apps/docs/mint.json
  apps/docs/platform/build.mdx
  apps/docs/platform/run.mdx
  apps/docs/platform/share.mdx
Labels: documentation
