Repository codemod/codemod, pull requests merged in 2024-12, with the labels that each got.

#1385 fix(cli): when error opening a link - show it in console
  .changeset/eleven-zoos-wonder.md
  apps/cli/src/auth-utils.ts
  apps/cli/src/commands/feedback.ts
  apps/cli/src/commands/learn.ts
  apps/cli/src/commands/login.ts
  apps/cli/src/commands/run.ts
  apps/cli/src/credentials-storage.ts
  apps/cli/src/utils/open.ts
  apps/cli/test/credentialsStorage.test.ts
  apps/cli/test/credentialsStorageKeytar.test.ts
  pnpm-lock.yaml
Labels: bug

#1429 feat(website): add google ads gtag
  apps/frontend/app/layout.tsx
Labels: website

#1427 feat(navbar): Added solution dropdown to navbar
  apps/frontend/components/global/HoverArrow/index.tsx
  apps/frontend/components/global/Navigation/DesktopNavigation.tsx
  apps/frontend/components/global/Navigation/MobileNavigation.tsx
  apps/frontend/components/global/Navigation/NavigationDropdown.tsx
  apps/frontend/components/global/Navigation/PlatformButtonWithDropdown.tsx
  apps/frontend/components/global/Navigation/SolutionButtonWithDropdown.tsx
  apps/frontend/components/sections/sectionComponents/SectionFullWidthMedia.tsx
  apps/frontend/components/sections/sectionComponents/Testimonials.tsx
  apps/frontend/styles/globals.css
Labels: website

#1434 fix(frontend): Decrease features section validation limit
  apps/frontend/sanity/schemas/sections/features.ts
Labels: website

#1428 fix: fixed the overlapping text over the button inside PromptForm
  apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/PromptForm.tsx
Labels: studio
