Repository codemod/codemod, pull requests merged in 2025-01, with the labels that each got.

#1436 chore(navbar): Remove extra links
  apps/frontend/components/global/Navigation/SolutionButtonWithDropdown.tsx
Labels: website

#1440 feat: add changeset for #1418 PR changes
  .changeset/spotty-donuts-tap.md
  pnpm-lock.yaml
Labels: cli

#1444 fix: hide example heading in markdown purview in registry card
  apps/frontend/components/templates/Registry/helpers.ts
Labels: web registry

#1443 chore(apps/cli): update README.md template in starter boilerplate for codemod init
  .changeset/honest-vans-hope.md
  packages/utilities/src/package-boilerplate.ts
Labels: cli
